/**
 * Default Achievement level milestones, corporate networking visual themes,
 * and inspirational messaging for all 15 matrix levels.
 * Compliant: No guaranteed earnings, return promises, or misleading investment claims.
 */

export const DEFAULT_ACHIEVEMENT_LEVELS = [
  {
    level: 1,
    title: 'Journey Started',
    subtitle: 'Foundation Builder',
    badgeName: 'BRONZE PIONEER',
    theme: 'emerald',
    primaryColor: '#10B981',
    gradientBg: 'linear-gradient(135deg, #064E3B 0%, #022C22 50%, #0F172A 100%)',
    accentColor: '#34D399',
    borderGradient: 'linear-gradient(135deg, #10B981, #059669)',
    badgeBg: '#065F46',
    badgeText: '#A7F3D0',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 1!',
    motivationalMessage: 'Your journey has begun. Keep inspiring, connecting, and growing your network.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 3,
  },
  {
    level: 2,
    title: 'Team Builder',
    subtitle: 'Network Collaborator',
    badgeName: 'SILVER CONNECTOR',
    theme: 'cyan',
    primaryColor: '#06B6D4',
    gradientBg: 'linear-gradient(135deg, #164E63 0%, #083344 50%, #0F172A 100%)',
    accentColor: '#22D3EE',
    borderGradient: 'linear-gradient(135deg, #06B6D4, #0891B2)',
    badgeBg: '#155E75',
    badgeText: '#CFFAFE',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 2!',
    motivationalMessage: 'Great achievements in business are never done by one person, they are done by a team of people.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 9,
  },
  {
    level: 3,
    title: 'Growth Champion',
    subtitle: 'Momentum Creator',
    badgeName: 'GOLD MOMENTUM',
    theme: 'blue',
    primaryColor: '#3B82F6',
    gradientBg: 'linear-gradient(135deg, #1E3A8A 0%, #172554 50%, #0F172A 100%)',
    accentColor: '#60A5FA',
    borderGradient: 'linear-gradient(135deg, #3B82F6, #2563EB)',
    badgeBg: '#1E40AF',
    badgeText: '#DBEAFE',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 3!',
    motivationalMessage: 'Consistent positive action creates unstoppable momentum. Your vision is turning into reality.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 27,
  },
  {
    level: 4,
    title: 'Leadership Spark',
    subtitle: 'Visionary Partner',
    badgeName: 'PLATINUM LEADER',
    theme: 'indigo',
    primaryColor: '#6366F1',
    gradientBg: 'linear-gradient(135deg, #312E81 0%, #1E1B4B 50%, #0F172A 100%)',
    accentColor: '#818CF8',
    borderGradient: 'linear-gradient(135deg, #6366F1, #4F46E5)',
    badgeBg: '#3730A3',
    badgeText: '#E0E7FF',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 4!',
    motivationalMessage: 'Leadership is the capacity to translate vision into reality and inspire strength in others.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 81,
  },
  {
    level: 5,
    title: 'Network Pillar',
    subtitle: 'Organizational Backbone',
    badgeName: 'SAPPHIRE PILLAR',
    theme: 'purple',
    primaryColor: '#A855F7',
    gradientBg: 'linear-gradient(135deg, #581C87 0%, #3B0764 50%, #0F172A 100%)',
    accentColor: '#C084FC',
    borderGradient: 'linear-gradient(135deg, #A855F7, #9333EA)',
    badgeBg: '#6B21A8',
    badgeText: '#F3E8FF',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 5!',
    motivationalMessage: 'You do not build a network; you build people, and the people build the network.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 243,
  },
  {
    level: 6,
    title: 'Rising Leader',
    subtitle: 'Empowerment Specialist',
    badgeName: 'RUBY CATALYST',
    theme: 'fuchsia',
    primaryColor: '#D946EF',
    gradientBg: 'linear-gradient(135deg, #701A75 0%, #4A044E 50%, #0F172A 100%)',
    accentColor: '#E879F9',
    borderGradient: 'linear-gradient(135deg, #D946EF, #C026D3)',
    badgeBg: '#86198F',
    badgeText: '#FAE8FF',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 6!',
    motivationalMessage: 'Your influence expands with every person you empower. Keep leading with purpose and humility.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 729,
  },
  {
    level: 7,
    title: 'Network Builder',
    subtitle: 'Bridge to Success',
    badgeName: 'EMERALD ARCHITECT',
    theme: 'rose',
    primaryColor: '#F43F5E',
    gradientBg: 'linear-gradient(135deg, #881337 0%, #4C0519 50%, #0F172A 100%)',
    accentColor: '#FB7185',
    borderGradient: 'linear-gradient(135deg, #F43F5E, #E11D48)',
    badgeBg: '#9F1239',
    badgeText: '#FFE4E6',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 7!',
    motivationalMessage: 'True networkers build bridges where others see boundaries. Your leadership speaks through action.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 2187,
  },
  {
    level: 8,
    title: 'Milestone Master',
    subtitle: 'Strategic Influencer',
    badgeName: 'TOPAZ STRATEGIST',
    theme: 'amber',
    primaryColor: '#F59E0B',
    gradientBg: 'linear-gradient(135deg, #78350F 0%, #451A03 50%, #0F172A 100%)',
    accentColor: '#FBBF24',
    borderGradient: 'linear-gradient(135deg, #F59E0B, #D97706)',
    badgeBg: '#92400E',
    badgeText: '#FEF3C7',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 8!',
    motivationalMessage: 'Milestones are living proof that discipline, vision, and consistency will always triumph.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 6561,
  },
  {
    level: 9,
    title: 'Growth Leader',
    subtitle: 'Network Ambassador',
    badgeName: 'AMBER AMBASSADOR',
    theme: 'orange',
    primaryColor: '#F97316',
    gradientBg: 'linear-gradient(135deg, #7C2D12 0%, #431407 50%, #0F172A 100%)',
    accentColor: '#FB923C',
    borderGradient: 'linear-gradient(135deg, #F97316, #EA580C)',
    badgeBg: '#9A3412',
    badgeText: '#FFEDD5',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 9!',
    motivationalMessage: 'Excellence is not an act, but a habit. You have set a new benchmark for excellence in our network.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 19683,
  },
  {
    level: 10,
    title: 'Executive Leader',
    subtitle: 'Visionary Director',
    badgeName: 'DIAMOND EXECUTIVE',
    theme: 'gold',
    primaryColor: '#EAB308',
    gradientBg: 'linear-gradient(135deg, #713F12 0%, #422006 50%, #0F172A 100%)',
    accentColor: '#FACC15',
    borderGradient: 'linear-gradient(135deg, #FACC15, #EAB308)',
    badgeBg: '#854D0E',
    badgeText: '#FEF9C3',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 10!',
    motivationalMessage: 'Real leadership is inspiring others to dream more, learn more, do more, and become more.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 59049,
  },
  {
    level: 11,
    title: 'Elite Achiever',
    subtitle: 'Strategic Vanguard',
    badgeName: 'BLUE DIAMOND VANGUARD',
    theme: 'platinum',
    primaryColor: '#E2E8F0',
    gradientBg: 'linear-gradient(135deg, #334155 0%, #0F172A 50%, #020617 100%)',
    accentColor: '#F8FAFC',
    borderGradient: 'linear-gradient(135deg, #E2E8F0, #94A3B8)',
    badgeBg: '#475569',
    badgeText: '#F8FAFC',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 11!',
    motivationalMessage: 'Exceptional success belongs to those who venture boldly and elevate their entire community.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 177147,
  },
  {
    level: 12,
    title: 'Matrix Champion',
    subtitle: 'Community Icon',
    badgeName: 'BLACK DIAMOND CHAMPION',
    theme: 'titanium',
    primaryColor: '#94A3B8',
    gradientBg: 'linear-gradient(135deg, #1E293B 0%, #0F172A 50%, #000000 100%)',
    accentColor: '#CBD5E1',
    borderGradient: 'linear-gradient(135deg, #94A3B8, #64748B)',
    badgeBg: '#334155',
    badgeText: '#F1F5F9',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 12!',
    motivationalMessage: 'Champions do not show up just to win; they show up to elevate every life they touch.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 531441,
  },
  {
    level: 13,
    title: 'Network Excellence',
    subtitle: 'Honorary Mentor',
    badgeName: 'ROYAL RUBY MENTOR',
    theme: 'ruby',
    primaryColor: '#E11D48',
    gradientBg: 'linear-gradient(135deg, #4C0519 0%, #1C0006 50%, #0B0F19 100%)',
    accentColor: '#FB7185',
    borderGradient: 'linear-gradient(135deg, #E11D48, #BE123C)',
    badgeBg: '#881337',
    badgeText: '#FFE4E6',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 13!',
    motivationalMessage: 'Excellence is doing ordinary things extraordinarily well with unwavering dedication.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 1594323,
  },
  {
    level: 14,
    title: 'Master Networker',
    subtitle: 'Global Influencer',
    badgeName: 'CROWN AMBASSADOR',
    theme: 'diamond',
    primaryColor: '#38BDF8',
    gradientBg: 'linear-gradient(135deg, #075985 0%, #032A44 50%, #020617 100%)',
    accentColor: '#7DD3FC',
    borderGradient: 'linear-gradient(135deg, #38BDF8, #0284C7)',
    badgeBg: '#0369A1',
    badgeText: '#E0F2FE',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 14!',
    motivationalMessage: 'Mastery comes from dedication, vision, and relentless commitment to collective progress.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 4782969,
  },
  {
    level: 15,
    title: 'Pinnacle of Success',
    subtitle: 'Ultimate Legend',
    badgeName: 'GRAND CROWN LEGEND',
    theme: 'crown',
    primaryColor: '#F59E0B',
    gradientBg: 'linear-gradient(135deg, #78350F 0%, #3B1602 40%, #000000 100%)',
    accentColor: '#FDE047',
    borderGradient: 'linear-gradient(135deg, #FDE047, #EAB308, #CA8A04)',
    badgeBg: '#92400E',
    badgeText: '#FEF3C7',
    congratulationsText: 'CONGRATULATIONS ON REACHING LEVEL 15!',
    motivationalMessage: 'The highest pinnacle of network leadership. You have forged a lasting legacy and transformed thousands of lives.',
    tagline: 'People Grow. Dreams Grow.',
    capacity: 14348907,
  },
];

/**
 * Merges static level definitions with custom templates from database.
 */
export function getLevelAchievementConfig(level, customTemplate = null) {
  const base = DEFAULT_ACHIEVEMENT_LEVELS.find((l) => l.level === Number(level)) || DEFAULT_ACHIEVEMENT_LEVELS[0];
  if (!customTemplate) return base;

  return {
    ...base,
    title: customTemplate.title || base.title,
    subtitle: customTemplate.subtitle || base.subtitle,
    badgeName: customTemplate.badgeName || base.badgeName,
    congratulationsText: customTemplate.congratulationsText || base.congratulationsText,
    motivationalMessage: customTemplate.motivationalMessage || base.motivationalMessage,
    tagline: customTemplate.tagline || base.tagline,
    customBackgroundUrl: customTemplate.customBackgroundUrl || '',
    allowReferralQr: customTemplate.allowReferralQr !== false,
    allowReferralCode: customTemplate.allowReferralCode !== false,
  };
}

/**
 * Builds a clean, compliant social media caption for sharing.
 * Strictly avoids any raw Cloudinary/media URLs.
 */
export function buildAchievementCaption({ member, levelConfig, referralLink = '' }) {
  const memberName = member?.fullName || 'NexVia Partner';
  const levelNum = levelConfig.level;
  const levelTitle = levelConfig.title;
  const memberCode = member?.mlmCode || '';

  let caption = `🎉 Proud Moment! Milestone Achieved!

I am delighted to announce that I have successfully completed Level ${levelNum} (${levelTitle}) in the NexVia Network!

"${levelConfig.motivationalMessage}"

Building together, growing together. People Grow. Dreams Grow.`;

  if (referralLink && memberCode) {
    caption += `\n\n🚀 Join my growing network with Sponsor Code: *${memberCode}*\n👉 Register here: ${referralLink}`;
  }

  caption += `\n\n#NexVia #Level${levelNum} #Achievement #NetworkMarketing #Leadership #Milestone #CommunityGrowth`;

  return caption;
}
