import { LayoutDashboard, Users, Heart, Settings, User, MapPin, IndianRupee, ClipboardList, Target, Layout, FileText, ShieldCheck, Mail, Sparkles, Wallet, ShoppingBag, BadgeCheck, Briefcase, Building2, History, BarChart3, Calendar, Image as ImageIcon, Bell, Percent, SlidersHorizontal, Network, CreditCard } from 'lucide-react';
export const PUBLIC_LINKS = [
    { name: 'Home', href: '/' },
    { name: 'About', href: '/about' },
    { name: 'Programs', href: '/programs' },
    { name: 'Contact', href: '/contact' },
];
export const MEMBER_DASHBOARD_LINKS = [
    { name: 'Overview', icon: LayoutDashboard, href: '/member/dashboard' },
    { name: 'My Group', icon: Users, href: '/member/my-group' },
    { name: 'Campaigns', icon: Target, href: '/member/campaigns' },
    { name: 'My Receipt', icon: FileText, href: '/member/receipt' },
    { name: 'Resources', icon: Heart, href: '/member/resources' },
    { name: 'My Profile', icon: User, href: '/member/dashboard/profile' },
    { name: 'My ID Card', icon: BadgeCheck, href: '/id-card' },
    { name: 'My Health Card', icon: Heart, href: '/member/health-card' },
    { name: 'My Health Bookings', icon: Calendar, href: '/member/dashboard/health-bookings' },
    { name: 'Verify Membership', icon: ShieldCheck, href: '/member/verify' },
    { name: 'Products', icon: ShoppingBag, href: '/member/products' },
    { name: 'My Orders', icon: ClipboardList, href: '/member/orders' },
    { name: 'Share Products', icon: Sparkles, href: '/member/share-products' },
    { name: 'Referral Links', icon: FileText, href: '/member/referral-links' },
    { name: 'Referral Orders', icon: Users, href: '/member/referral-orders' },
    { name: 'Commission & Earnings', icon: Wallet, href: '/member/earnings' },
    { name: 'Settings', icon: Settings, href: '/member/settings' },
];
export const EMPLOYEE_DASHBOARD_LINKS = [
    { name: 'Overview', icon: LayoutDashboard, href: '/employee/dashboard' },
    { name: 'Attendance', icon: ShieldCheck, href: '/employee/attendance' },
    { name: 'Leave Management', icon: Calendar, href: '/employee/leaves' },
    { name: 'Member Requests', icon: Heart, href: '/employee/requests' },
    { name: 'My Groups', icon: Layout, href: '/employee/groups' },
    { name: 'Women Members', icon: Users, href: '/employee/members' },
    { name: 'My Wallet', icon: Wallet, href: '/employee/wallet' },
    { name: 'Daily Reports', icon: ClipboardList, href: '/employee/reports' },
    { name: 'Campaigns', icon: Target, href: '/employee/campaigns' },
    { name: 'Documents', icon: FileText, href: '/employee/dashboard/documents' },
    { name: 'My Profile', icon: User, href: '/employee/dashboard/profile' },
];
export const ADMIN_DASHBOARD_LINKS = [
    // CORE
    { section: 'Core', name: 'Overview', icon: LayoutDashboard, href: '/admin/dashboard' },
    { section: 'Core', name: 'Network Tree', icon: MapPin, href: '/admin/network' },
    { section: 'Core', name: 'Activity Reports', icon: FileText, href: '/admin/reports' },
    // USERS
    { section: 'Users', name: 'All Users', icon: Users, href: '/admin/users' },
    { section: 'Users', name: 'User Control', icon: SlidersHorizontal, href: '/admin/user-control' },
    { section: 'Users', name: 'Vendors', icon: ShieldCheck, href: '/admin/vendors' },
    { section: 'Users', name: 'Sub-Vendors', icon: Layout, href: '/admin/sub-vendors' },
    { section: 'Users', name: 'Employees', icon: ClipboardList, href: '/admin/employees' },
    { section: 'Users', name: 'District Coordinators', icon: MapPin, href: '/admin/district-coordinators' },
    { section: 'Users', name: 'Staff Management', icon: Users, href: '/admin/staff' },
    { section: 'Users', name: 'All Groups', icon: Layout, href: '/admin/groups' },
    { section: 'Users', name: 'All Members', icon: Users, href: '/admin/members' },
    { section: 'Users', name: 'ABHA', icon: Heart, href: '/admin/abha' },
    // HRMS
    { section: 'HRMS', name: 'HRMS Dashboard', icon: LayoutDashboard, href: '/admin/hrms/dashboard' },
    { section: 'HRMS', name: 'HRMS Employees', icon: Users, href: '/admin/hrms/employees' },
    { section: 'HRMS', name: 'HRMS Attendance', icon: ShieldCheck, href: '/admin/hrms/attendance' },
    { section: 'HRMS', name: 'HRMS Reports', icon: FileText, href: '/admin/hrms/reports' },
    { section: 'HRMS', name: 'HRMS Leaves', icon: ClipboardList, href: '/admin/hrms/leaves' },
    // HR & RECRUITMENT
    { section: 'Recruitment', name: 'Vacancies', icon: Briefcase, href: '/admin/careers/vacancies' },
    { section: 'Recruitment', name: 'Applications', icon: Users, href: '/admin/careers/applications' },
    // RECRUITMENT PARTNER CRM MODULE (NATIVE ADMIN MODULE)
    { section: 'Recruitment CRM', name: 'CRM Dashboard', icon: Briefcase, href: '/admin/recruitment' },
    { section: 'Recruitment CRM', name: 'Employer Clients', icon: Building2, href: '/admin/recruitment/companies' },
    { section: 'Recruitment CRM', name: 'Job Requirements', icon: Briefcase, href: '/admin/recruitment/jobs' },
    { section: 'Recruitment CRM', name: 'Partner Directory', icon: Users, href: '/admin/recruitment/partners' },
    { section: 'Recruitment CRM', name: 'Candidate Pipeline', icon: Users, href: '/admin/recruitment/candidates' },
    { section: 'Recruitment CRM', name: 'Partner Payouts', icon: Wallet, href: '/admin/recruitment/payouts' },
    { section: 'Recruitment CRM', name: 'CRM Settings', icon: Settings, href: '/admin/recruitment/settings' },
    // OPERATIONS
    { section: 'Operations', name: 'Manual Authorization', icon: ShieldCheck, href: '/admin/authorization' },
    { section: 'Operations', name: 'Memberships', icon: IndianRupee, href: '/admin/memberships' },
    { section: 'Operations', name: 'Campaigns', icon: Target, href: '/admin/campaigns' },
    { section: 'Operations', name: 'Manage Projects', icon: Sparkles, href: '/admin/projects' },
    { section: 'Operations', name: 'Support Desk', icon: ClipboardList, href: '/admin/support-desk' },
    { section: 'Operations', name: 'Support Queries', icon: Mail, href: '/admin/support-requests' },
    // SYSTEM & FINANCE
    { section: 'System & Finance', name: 'Payment Config', icon: IndianRupee, href: '/admin/payment-config' },
    { section: 'System & Finance', name: 'Offline Payments', icon: ClipboardList, href: '/admin/offline-payments' },
    { section: 'System & Finance', name: 'Healthcare Settlements', icon: Wallet, href: '/admin/finance/health' },
    { section: 'System & Finance', name: 'Finance Control', icon: Wallet, href: '/admin/finance' },
    { section: 'System & Finance', name: 'Dynamic Forms', icon: ClipboardList, href: '/admin/forms' },
    { section: 'System & Finance', name: 'CMS Manage', icon: Settings, href: '/admin/cms' },
    { section: 'System & Finance', name: 'Gallery Manage', icon: ImageIcon, href: '/admin/gallery' },
    { section: 'System & Finance', name: 'Team Manage', icon: Users, href: '/admin/team-manage' },
    { section: 'System & Finance', name: 'My Profile', icon: User, href: '/admin/profile' },
    // WEBSITE MANAGEMENT
    { section: 'Website Management', name: 'Popup Notice Manager', icon: Bell, href: '/admin/popup-notices' },
    // ADMIN MANAGEMENT
    { section: 'Admin Management', name: 'Operations Admins', icon: User, href: '/admin/operations-admins' },
    { section: 'Admin Management', name: 'Permissions', icon: ShieldCheck, href: '/admin/permissions' },
    { section: 'Admin Management', name: 'Assignments', icon: MapPin, href: '/admin/assignments' },
    { section: 'Admin Management', name: 'Activity Logs', icon: ClipboardList, href: '/admin/activity-logs' },
    // COMMUNICATION CENTER
    { section: 'Communication Center', name: 'Email Campaigns', icon: Mail, href: '/admin/communication/campaigns' },
    { section: 'Communication Center', name: 'Campaign History', icon: History, href: '/admin/communication/history' },
    { section: 'Communication Center', name: 'Email Templates', icon: FileText, href: '/admin/communication/templates' },
    { section: 'Communication Center', name: 'Delivery Logs', icon: ClipboardList, href: '/admin/communication/logs' },
    { section: 'Communication Center', name: 'Analytics Dashboard', icon: BarChart3, href: '/admin/communication/analytics' },
    { section: 'Order Management', name: 'Manage Products', icon: ShoppingBag, href: '/admin/products' },
    { section: 'Order Management', name: 'Member Orders', icon: ClipboardList, href: '/admin/orders' },
    { section: 'Order Management', name: 'Referral Orders', icon: Users, href: '/admin/referral-orders' },
    { section: 'Order Management', name: 'Commission Management', icon: Wallet, href: '/admin/commissions' },
    // HEALTH NETWORK
    { section: 'Health Network', name: 'Health Vendors', icon: ShieldCheck, href: '/admin/health-vendors' },
    { section: 'Health Network', name: 'Health Sub-Vendors', icon: Layout, href: '/admin/health-sub-vendors' },
    { section: 'Health Network', name: 'Health Team Leaders', icon: Users, href: '/admin/health-team-leaders' },
    { section: 'Health Network', name: 'Health Executives', icon: ClipboardList, href: '/admin/health-executives' },
    { section: 'Health Network', name: 'Health Partners', icon: Heart, href: '/admin/health-partners' },
    { section: 'Health Network', name: 'Categories', icon: Layout, href: '/admin/health-categories' },
    { section: 'Health Network', name: 'Plans Manager', icon: ClipboardList, href: '/admin/health-plans' },
    { section: 'Health Network', name: 'Commissions', icon: Wallet, href: '/admin/health-network' },
    { section: 'Health Network', name: 'Discount Splits Settings', icon: Percent, href: '/admin/health-service-commissions' },
    // CORPORATE PLATFORM
    { section: 'Corporate Platform', name: 'Corporate Control Center', icon: Briefcase, href: '/admin/corporate' },
    // MLM & FD PLATFORM
    { section: 'MLM & FD Platform', name: 'MLM Overview', icon: LayoutDashboard, href: '/admin/mlm' },
    { section: 'MLM & FD Platform', name: 'MLM Members', icon: Users, href: '/admin/mlm/members' },
    { section: 'MLM & FD Platform', name: 'KYC Verification', icon: ShieldCheck, href: '/admin/mlm/kyc' },
    { section: 'MLM & FD Platform', name: 'FD Applications', icon: BadgeCheck, href: '/admin/mlm/fd' },
    { section: 'MLM & FD Platform', name: '3×15 Matrix', icon: Network, href: '/admin/mlm/matrix' },
    { section: 'MLM & FD Platform', name: 'MLM Rewards', icon: IndianRupee, href: '/admin/mlm/rewards' },
    { section: 'MLM & FD Platform', name: 'Level 1–15 Config', icon: SlidersHorizontal, href: '/admin/mlm/levels' },
    { section: 'MLM & FD Platform', name: 'MLM Wallet', icon: Wallet, href: '/admin/mlm/wallet' },
    { section: 'MLM & FD Platform', name: 'Withdrawal Payouts', icon: IndianRupee, href: '/admin/mlm/withdrawals' },
    { section: 'MLM & FD Platform', name: 'Platform Payments', icon: CreditCard, href: '/admin/mlm/payments' },
    { section: 'MLM & FD Platform', name: 'MLM Reports', icon: BarChart3, href: '/admin/mlm/reports' },
    { section: 'MLM & FD Platform', name: 'Training & Marketing', icon: Sparkles, href: '/admin/mlm/training' },
    { section: 'MLM & FD Platform', name: 'MLM CMS', icon: FileText, href: '/admin/mlm/cms' },
    { section: 'MLM & FD Platform', name: 'MLM Notifications', icon: Bell, href: '/admin/mlm/notifications' },
    { section: 'MLM & FD Platform', name: 'MLM Audit Logs', icon: History, href: '/admin/mlm/audit-logs' },
];
export const VENDOR_DASHBOARD_LINKS = [
    { name: 'Overview', icon: LayoutDashboard, href: '/vendor/dashboard' },
    { name: 'Network Mapping', icon: MapPin, href: '/vendor/dashboard/network' },
    { name: 'My Campaigns', icon: Target, href: '/vendor/dashboard/campaigns' },
    { name: 'Sub-Vendors', icon: Layout, href: '/vendor/dashboard/sub-vendors' },
    { name: 'Employees', icon: ClipboardList, href: '/vendor/dashboard/employees' },
    { name: 'Groups', icon: Users, href: '/vendor/dashboard/groups' },
    { name: 'Daily Reports', icon: ClipboardList, href: '/vendor/dashboard/reports' },
    { name: 'Members', icon: User, href: '/vendor/dashboard/members' },
    { name: 'Payments', icon: IndianRupee, href: '/vendor/dashboard/payments' },
    { name: 'My Wallet', icon: Wallet, href: '/vendor/dashboard/wallet' },
    { name: 'Documents', icon: FileText, href: '/vendor/dashboard/documents' },
    { name: 'My Profile', icon: User, href: '/vendor/dashboard/profile' },
    { name: 'Support', icon: Heart, href: '/vendor/dashboard/support' },
];
export const SUBVENDOR_DASHBOARD_LINKS = [
    { name: 'Overview', icon: LayoutDashboard, href: '/sub-vendor/dashboard' },
    { name: 'Network Mapping', icon: MapPin, href: '/sub-vendor/dashboard/network' },
    { name: 'Campaigns', icon: Target, href: '/sub-vendor/dashboard/campaigns' },
    { name: 'Employees', icon: ClipboardList, href: '/sub-vendor/dashboard/employees' },
    { name: 'Groups', icon: Users, href: '/sub-vendor/dashboard/groups' },
    { name: 'Daily Reports', icon: ClipboardList, href: '/sub-vendor/dashboard/reports' },
    { name: 'Members', icon: User, href: '/sub-vendor/dashboard/members' },
    { name: 'Payments', icon: IndianRupee, href: '/sub-vendor/dashboard/payments' },
    { name: 'My Wallet', icon: Wallet, href: '/sub-vendor/dashboard/wallet' },
    { name: 'Documents', icon: FileText, href: '/sub-vendor/dashboard/documents' },
    { name: 'My Profile', icon: User, href: '/sub-vendor/dashboard/profile' },
    { name: 'Support', icon: Heart, href: '/sub-vendor/dashboard/support' },
];
export const HEALTH_PARTNER_DASHBOARD_LINKS = [
    { name: 'Overview', icon: LayoutDashboard, href: '/health-partner/dashboard' },
    { name: 'Scan Health Card', icon: ShieldCheck, href: '/health-partner/qr-verify' },
    { name: 'Medical Records', icon: FileText, href: '/health-partner/records' },
    { name: 'Finance & Settlements', icon: Wallet, href: '/health-partner/finance' },
    { name: 'Audit Reports', icon: BarChart3, href: '/health-partner/reports' },
    { name: 'Branches', icon: MapPin, href: '/health-partner/branches' },
    { name: 'Staff Management', icon: Users, href: '/health-partner/staff' },
    { name: 'Services/Pricing', icon: ClipboardList, href: '/health-partner/services' },
    { name: 'Certificate', icon: BadgeCheck, href: '/health-partner/certificate' },
    { name: 'My Profile', icon: User, href: '/health-partner/profile' },
];
export const HEALTH_TEAM_LEADER_DASHBOARD_LINKS = [
    { name: 'Overview', icon: LayoutDashboard, href: '/health-team-leader/dashboard' },
    { name: 'Network Mapping', icon: MapPin, href: '/health-team-leader/dashboard/network' },
    { name: 'My Services', icon: Target, href: '/health-team-leader/dashboard/campaigns' },
    { name: 'Health Executives', icon: ClipboardList, href: '/health-team-leader/dashboard/employees' },
    { name: 'Hospitals', icon: User, href: '/health-team-leader/dashboard/members' },
    { name: 'Commission', icon: IndianRupee, href: '/health-team-leader/dashboard/payments' },
    { name: 'My Wallet', icon: Wallet, href: '/health-team-leader/dashboard/wallet' },
    { name: 'Documents', icon: FileText, href: '/health-team-leader/dashboard/documents' },
    { name: 'My Profile', icon: User, href: '/health-team-leader/dashboard/profile' },
    { name: 'Support', icon: Heart, href: '/health-team-leader/dashboard/support' },
];
